name       : python3-pylast
version    : 4.3.0
release    : 9
source     :
    - https://pypi.io/packages/source/p/pylast/pylast-4.3.0.tar.gz : 71fd876e3753009bd10ea55b3f8f7c5d68591ee18a4127d257fc4a418010aa5c
license    : Apache-2.0
component  : programming.python
summary    : A Python interface to Last.fm and Libre.fm
description: |
    A Python interface to Last.fm and other API-compatible websites such as Libre.fm.
builddeps  :
    - pkgconfig(python3)
    - python-flaky
    - python-pytest
    - python-setuptools-scm
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
