name       : python3-pylast
version    : 1.1.0
release    : 1
source     :
    - https://github.com/pylast/pylast/archive/1.1.0.tar.gz : 0c8ec43d931624d65582e38d4e0c10f8a1215a4a1caa9d7841642d2d083d1610
license    : Apache-2.0
summary    : last.fm python plugin
description: |
    last.fm python plugin
builddeps  :
    - python3-devel
    - python3-setuptools
    - python-six
setup      : |
build      : |
    python3 setup.py build
install    : |
    python3 setup.py install --root=%installroot% --optimize=1
