name       : python3-pylast
version    : 4.1.0
release    : 8
source     :
    - https://pypi.io/packages/source/p/pylast/pylast-4.1.0.tar.gz : ad084aec1bf7e307bc42d7cc1a003851f5bee1ad24fb697a9fdc300bbfe63932
license    : Apache-2.0
component  : programming.python
summary    : last.fm python plugin
description: |
    last.fm python plugin
builddeps  :
    - pkgconfig(python3)
    - python-setuptools-scm
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
