name       : python3-pylast
version    : 1.3.0
release    : 4
source     :
    - https://github.com/pylast/pylast/archive/1.3.0.tar.gz : fbd999081f4adba9a920bdc33e8d860fc7558f4f5a97297673487ac64f435495
license    : Apache-2.0
component  : programming.python
summary    : last.fm python plugin
description: |
    last.fm python plugin
builddeps  :
    - pkgconfig(python3)
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
