name       : python3-pylast
version    : 1.3.0
release    : 3
source     :
    - https://github.com/pylast/pylast/archive/1.3.0.tar.gz : fbd999081f4adba9a920bdc33e8d860fc7558f4f5a97297673487ac64f435495
license    : Apache-2.0
summary    : last.fm python plugin
description: |
    last.fm python plugin
builddeps  :
    - pkgconfig(python-3.5)
    - python3-setuptools
    - python-six
setup      : |
build      : |
    python3 setup.py build
install    : |
    python3 setup.py install --root=%installroot% --optimize=1
