name       : python3-pylast
version    : 3.1.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/c1/3b/05414f6c406d571604a6ee19530ba0a0bd35a8c2cae158ffac0caaa74179/pylast-3.1.0.tar.gz : 7eb58682beccc0052c3284aba64a9a6454b5e89706f789ebeb2403dc1045606a
license    : Apache-2.0
component  : programming.python
summary    : last.fm python plugin
description: |
    last.fm python plugin
builddeps  :
    - pkgconfig(python3)
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
